### ISSUE TITLE
1.18.2? 1.19.2? 1.17.x or lower?

### ISSUE THREAD

**Issue by ConqAra** [MrKacafirekCZ/doggo-mod-overhauled#1]
Will a backport for 1.18.2 be available in the future?

**Comment by MrKacafirekCZ** [comment]
Hello, it's very likely that there will be a 1.18.2 version in the future. It's also very likely that there will be a 1.19.2 version since 1.19.3 had some changes to the code. However I don't believe there will be a 1.17.x or lower version in the future.

**Comment by MrKacafirekCZ** [comment]
Hello again, version 1.18.2 and 1.19.2 have been released.
