### ISSUE TITLE
[FEATURE] 1.20 support?

### ISSUE THREAD

**Issue by Thefatsparrow** [MrKacafirekCZ/doggo-mod-overhauled#20]
**Is your feature request related to a problem? Please describe.**
when will you add 1.20?

**Describe the solution you'd like**
i would love it if you would update this mod to 1.20

**Describe alternatives you've considered**
there are no alternatives

**Additional context**
1.20

**Comment by MrKacafirekCZ** [comment]
Hello, 1.20 is planned but right now I'm waiting for the whole mod situation to calm itself down.

**Comment by Thefatsparrow** [comment]
when you say mod situation do you mean the virus thing going round?

if you have already updated the mod for 1.20 and are waiting to publish it any chance i could test it for 1.20?

**Comment by MrKacafirekCZ** [comment]
> when you say mod situation do you mean the virus thing going round?

Yes

> ...any chance i could test it for 1.20?

No as I haven't done any work on 1.20. Right now I'm aiming for start of the July (maybe slightly later) to be the days of 1.20 development and some features from the issues list. By that time I hope the whole mod situation is going to be over and that there won't be any "sudden comebacks" of the virus between now and July.

**Comment by Thefatsparrow** [comment]
so it will be published in july? sorry the questions i just really love this mod. out of all the mods I use this is my favourite mod

**Comment by MrKacafirekCZ** [comment]
Development should start in July and hopefully an update should be released the same month.

**Comment by Thefatsparrow** [comment]
any updates on 1.20 support? have you started it yet?

thanks

**Comment by MrKacafirekCZ** [comment]
Doggo Mod Overhauled has been updated to 1.20 and 1.20.1

**Comment by Thefatsparrow** [comment]
you legend
