### ISSUE TITLE
[FEATURE] make dog bark randomly

### ISSUE THREAD

**Issue by Thefatsparrow** [MrKacafirekCZ/doggo-mod-overhauled#21]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
for your doggo dog to bark randomly for a couple of seconds just randomly barking

**Describe alternatives you've considered**
there are no alternatives

**Additional context**
maybe a way to stop the dog barking like petting him or something like that

**Comment by MrKacafirekCZ** [comment]
Hello, I might not be exactly understanding what this feature proposal should be. As far as I'm aware Minecraft dogs already bark. Is it possible for you to elaborate more on this?

**Comment by Thefatsparrow** [comment]
do they bark? ive never noticed lol ive only used this mod on 1.19.2 

when do they bark?

**Comment by Thefatsparrow** [comment]
i hope you've liked my other proposal requests!

**Comment by MrKacafirekCZ** [comment]
> do they bark? ive never noticed lol ive only used this mod on 1.19.2
> 
> when do they bark?

Minecraft dogs in vanilla already bark from time to time. This has not been changed in the mod and is exactly same as in vanilla. I'm probably missing some kind of key element of your feature proposal, is possible for you to describe in more detail?

**Comment by Thefatsparrow** [comment]
nope i just never heard the dog bark! i got my volume too low
