### ISSUE TITLE
[BUG] Mixin conflict with PuzzlesLib mod

### ISSUE THREAD

**Issue by Lieliel** [MrKacafirekCZ/doggo-mod-overhauled#23]
When this mod is installed, it conflicts with PuzzlesLib. It shows Mixin errors. No crash report and only happens when launching. The only fix I found is removing this mod and waiting for an update for either 1.19.4 or 1.20.0+

Was compatible before until I updated Fabric Loader and other mods, no new mods were installed. Already submitted a report to the other mod author and will look into the mixin framework since nothing was wrong upon looking at the mods.

Latest.log: https://gist.github.com/Lieliel/646c14d1196f921652bdbb03685fb071

 - Minecraft version: 1.19.4
 - Fabric 0.14.21
 - Doggo Mod Overhauled (Version: 4.1.0)
 - PuzzleLib 6.0.11: https://modrinth.com/mod/puzzles-lib/version/v6.0.11-1.19.4-Fabric

**Comment by MrKacafirekCZ** [comment]
Hello, I can confirm that this is a mixin conflict. Unfortunately I have no idea how to fix it as of right now.

**Comment by rainysux** [comment]
This also occurs on 1.20.

**Comment by Nude-Zenpai** [comment]
same i got this problem on 1.20 :'(

**Comment by MrKacafirekCZ** [comment]
This has been fixed in the next version.
