### ISSUE TITLE
[COMPATIBILITY] with texture pack

### ISSUE THREAD

**Issue by Thefatsparrow** [MrKacafirekCZ/doggo-mod-overhauled#24]
**Is your compatibility request related to a problem? Please describe.**
yes patrix does not work with doggo overhauled mod 

**Describe the solution you'd like**
to make them compatible

**Describe alternatives you've considered**
create a texture pack that uses patrix dog to put ontop of patrix texture pack

**The mod you'd like a compatibility with**
patrix and fresh animations

**Additional context**
patrix uses fresh animations but if you cant make it compatible with fresh animations how would i make patrix compatible with doggo mod overhauled? i could do it myself if you help me on what to change since ive never made a texture pack before

**Comment by MrKacafirekCZ** [comment]
Hello, I have two questions:
- Is this a mod or a texture pack?
- Is it possible for you to provide a link to said mod/texture pack?

**Comment by Thefatsparrow** [comment]
yea sure but its kind of hard to explain.

so the texture pack patrix uses custom entity models from another texture pack called fresh animations. i think it would work if i could find a way to change the wolf entity to the custom doggo entity in the texture pack itself

heres patrix 
https://www.curseforge.com/minecraft/texture-packs/patrix-32x

heres fresh animations
https://www.curseforge.com/minecraft/texture-packs/fresh-animations

patrix uses fresh animations without needing the fresh animations pack they have kind of merged if you can call it that

**Comment by Thefatsparrow** [comment]
there both texture packs

**Comment by MrKacafirekCZ** [comment]
Do these texture packs require optifine to run? I have to apologize but my experience with texture packs like these is very limited so it may not be as simple as I think.

But theoretically I think you should be able to copy exactly the same files of those packs and put them in a directory of the texture pack that matches the one for this mod. So if Minecraft's default wolf texture is at `assets/minecraft/textures/entity/wolf` you should be able to do `assets/doggomodoverhauled/textures/entity/doggo`. You would also need to rename the files exactly as they're [here](https://github.com/MrKacafirekCZ/doggo-mod-overhauled/tree/main/src/main/resources/assets/doggomodoverhauled/textures/entity/doggo).

**Comment by Thefatsparrow** [comment]
ahh thanks! and what about the custom animations? they do require optifine to run but i use these mods instead for fabric

would i rename the files for the animations to the same as the path you sent me?

thanks

https://www.curseforge.com/minecraft/mc-mods/entity-model-features

https://legacy.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric

**Comment by MrKacafirekCZ** [comment]
Yes, in theory it should work. If it doesn't work then there is a possibility that it requires more files and those can be anything like `shaders` or optifine specific files found in the `optifine` folder.

**Comment by MrKacafirekCZ** [comment]
Hello, checking whether the issue was resolved or not.

**Comment by Thefatsparrow** [comment]
Sorry I couldn’t get it to work the textures were all bugged. you can close this issue if you wantOn 4 Aug 2023, at 19:13, LordMrK ***@***.***> wrote:﻿
Hello, checking whether the issue was resolved or not.
