### ISSUE TITLE
[COMPATIBILITY] BetterEnd/BetterNether

### ISSUE THREAD

**Issue by edik1045** [MrKacafirekCZ/doggo-mod-overhauled#26]
The game will not launch with the mod, the issue is registerBlocks function (im getting "Non [a-z0-9/._-] character in path of location" in the log), removing it will crash the game, because it will try to register it as null (no shit) and it happens with betternether and betterend only.

EDIT: it happens with every mod that adds blocks

I want for the game to launch with it lmao

The solution is uninstalling doggyoverhauled

**The mod you'd like a compatibility with**

https://modrinth.com/mod/betternether

https://modrinth.com/mod/betterend

**Additional context**
It tries to register the block name as doggooverhaulted:betternether:blocknamehere

**Comment by MrKacafirekCZ** [comment]
Hello, this is a bug that seems to happen anytime any mod tries to add a new wood type.

**Comment by MrKacafirekCZ** [comment]
Related issue #27

**Comment by MrKacafirekCZ** [comment]
Bug fixed in versions 4.2.1 and 5.2.1 for Minecraft version 1.19.4 and 1.20.1
