### ISSUE TITLE
[COMPATIBILITY] Minecraft 1.20 crash with wilderwild 2.1.1

### ISSUE THREAD

**Issue by aotusoft** [MrKacafirekCZ/doggo-mod-overhauled#27]
First of all I'm sorry I modified the wilderwild's fabric.mod.json file so that it works on minecraft 1.20

Game crashed when Doggo Mod Overhauled and wilderwild exist at the same time

**Comment by aotusoft** [comment]
logs is here

[minecraft-exported-crash-info-2023-08-04T13-09-29.zip](https://github.com/MrKacafirekCZ/doggo-mod-overhauled/files/12257262/minecraft-exported-crash-info-2023-08-04T13-09-29.zip)

**Comment by MrKacafirekCZ** [comment]
Hello, this is a bug that seems to happen anytime any mod tries to add a new wood type.

**Comment by MrKacafirekCZ** [comment]
Bug fixed in versions 4.2.1 and 5.2.1 for Minecraft version 1.19.4 and 1.20.1
