### ISSUE TITLE
[FEATURE] Mining time of dog beds

### ISSUE THREAD

**Issue by nco2k** [MrKacafirekCZ/doggo-mod-overhauled#35]
you can mine dog beds bare handed, and it only takes a split second. it would make more sense to apply the same rules for dog beds, that you already use for dog bowls.

**Comment by MrKacafirekCZ** [comment]
1) Dog beds can be mined bare handed because normal beds can also be mined bare handed.
2) Dog bowls are made out of metal that's why you need a pickaxe. Dog beds are made out of wood and wool, both of which can be mined bare handed.

**Comment by nco2k** [comment]
ah i see. you modeled it after normal beds. makes sense.
