### ISSUE TITLE
[BUG] dog stretching when enemys aggro on him

### ISSUE THREAD

**Issue by Thefatsparrow** [MrKacafirekCZ/doggo-mod-overhauled#37]
**Describe the bug**
my dog stretched when enemys were targeting him but he wasn't targeting them and he died

**To Reproduce**
N/A

**Expected behavior**
doggo not stretching when enemys targeting him same with scratch

**Screenshots**

**Minecraft version and a list of all mods with their version:**
 - Minecraft version: 1.20.1
 - Doggo Mod Overhauled (Version: 5.2.2)
 - Sodium (Version: 0.5.3)

**Additional context**

**Comment by MrKacafirekCZ** [comment]
Hello, does it happen when the dog starts attacking and then switches into stretching mode? Or does it happen when the dog starts stretching and completely ignores any incoming attacks from mobs?

**Comment by Thefatsparrow** [comment]
﻿﻿It only happens when the dog is not targeting a zombie but the zombie is targeting him he begins to stretch and while he is stretching the zombie kills him I also use a mod called companion were if the dogs health is lower than 20% he won’t target enemy’s so for me it happens when the dog attacks a zombie then the zombie hits him and gets his health is lower than 20% the dog will stop targeting the zombie but the zombie is still targeting him so he will start stretching Isn’t there a way to make the dog not stretch or scratch when something is targeting it?On 23 Oct 2023, at 07:02, LordMrK ***@***.***> wrote:﻿
Hello, does it happen when the dog starts attacking and then switches into stretching mode? Or does it happen when the dog starts stretching and completely ignores any incoming attacks from mobs?

**Comment by MrKacafirekCZ** [comment]
All animations should get cancelled if a dog gets attacked by a mob or a player. I'm wondering whether the other mod you were using is causing some issues. May I get a Modrinth/Curseforge link to it?

**Comment by Thefatsparrow** [comment]
https://modrinth.com/mod/companion

**Comment by MrKacafirekCZ** [comment]
This bug should be fixed in the next version!
