### ISSUE TITLE
[BUG] Doggo not interested in fetch :(

### ISSUE THREAD

**Issue by theavandiepen** [MrKacafirekCZ/doggo-mod-overhauled#43]
**Describe the bug**
Doggo not interested in the tennis ball :( No matter how long I hold the tennis ball while looking at my dog, it doesn't do the play bow. It'll do everything else, including briefly opening its mouth, but it won't show any interest in playing fetch. (And won't go after my ball once thrown)

**Expected behavior**
When I look at my dog while holding a tennis ball, the dog will do a lil play bow, at which point I can throw the ball and the doggo will go and get it

**Minecraft version and a list of all mods with their version:**
 - Minecraft (Version: 1.20.1)
 - Doggo Mod Overhauled (Version: 5.2.2)

![Screenshot 2023-11-24 22 09 01](https://github.com/MrKacafirekCZ/doggo-mod-overhauled/assets/84762309/e2715aee-dc3f-4147-b7d0-4876ecbbad9f)
![Screenshot 2023-11-24 22 10 03](https://github.com/MrKacafirekCZ/doggo-mod-overhauled/assets/84762309/875e3a30-2740-41d0-917d-349b794210a3)
![Screenshot 2023-11-24 22 10 21](https://github.com/MrKacafirekCZ/doggo-mod-overhauled/assets/84762309/ef30ad4a-fb19-41d3-951d-6b853e34e5e5)
![Screenshot 2023-11-24 22 10 32](https://github.com/MrKacafirekCZ/doggo-mod-overhauled/assets/84762309/2f172bcb-8fa2-4df2-8638-3098fe12f2cc)

**Additional context**
I'm using the Quilt, not Fabric. Please let me know if you also need to know any datapacks or resource packs I'm using (although I would be surprised if any of them were causing the issue, as I already tested with and without Fresh Animations and that's the only one that affects wolves)

**Comment by MrKacafirekCZ** [comment]
Hello, issue identified. Currently working on a fix. It seems to be affecting all versions.

**Comment by theavandiepen** [comment]
Oh, thank goodness! I'm looking forward to when the fix is out :)

**Comment by MrKacafirekCZ** [comment]
This bug should be fixed in the next version!

**Comment by theavandiepen** [comment]
I can confirm that it is! Thank you!
