### ISSUE TITLE
[BUG] dog attacking creepers/ghasts/tamed doggos/tamed horses/players on the same team

### ISSUE THREAD

**Issue by Thefatsparrow** [MrKacafirekCZ/doggo-mod-overhauled#46]
**Describe the bug**
when you hit a creeper the dog goes to attack the creeper and the creeper always blows the dog up and dies

**To Reproduce**
go in creative get a doggo spawn a creeper and then hit the creeper and watch the doggo attack the creeper and get blown up

**Expected behavior**
i was expecting the dog to run away from the creeper or not attack it at all

**Screenshots**

**Minecraft version and a list of all mods with their version:**
 - Minecraft (Version: [1.20.1)
 - Doggo Mod Overhauled (Version: [5.3.0)
 - Mod Name (Version: [doggo-mod-overhauled-5.3.0])

**Additional context**

**Comment by Thefatsparrow** [comment]
https://www.curseforge.com/minecraft/mc-mods/sophisticated-wolves/files?page=1&pageSize=20 like this mod makes the wolf run away from a creeper

**Comment by Thefatsparrow** [comment]
and vanilla dogs dont attack creepers anyway! should be easy to implement hopefully

**Comment by Thefatsparrow** [comment]
are those all the vanilla features of a normal dog? cause if so yay!!!

**Comment by MrKacafirekCZ** [comment]
yes as far as I'm aware

**Comment by Thefatsparrow** [comment]
less go if there is any other missing vanilla features you should try to find out what they are and add them if possible

**Comment by Thefatsparrow** [comment]
https://minecraft.fandom.com/wiki/Wolf

that might help

**Comment by Thefatsparrow** [comment]
and i think vanilla tamed dogs kill sheep but im not sure

**Comment by Thefatsparrow** [comment]
and can you change the colour of their collar?

**Comment by Thefatsparrow** [comment]
found this might be useful

**Comment by MrKacafirekCZ** [comment]
> less go if there is any other missing vanilla features you should try to find out what they are and add them if possible

I already thought I did that but it seems like I missed some that aren't really that much obvious at first glance.

> https://minecraft.fandom.com/wiki/Wolf
> 
> that might help

Not really. The Minecraft developers are constantly changing and updating the game. A good example is breeding where this worked perfectly fine, then a new update comes out and suddenly it's broken without me touching it.

> Wolves can either attack (within 16 blocks) or flee (within 24 blocks) from [llamas](https://minecraft.fandom.com/wiki/Llama). The wolves' speed is increased by 50% whereas they flee.

This one should already be working in the current version 6.3.0.

> Wolves attack their targets running about at the player's walking speed and by leaping at them in exactly the same manner as [spiders](https://minecraft.fandom.com/wiki/Spider), but cause no damage while in midair
> 
> doggos dont leap so maybe you could add that if you wanted to

This one should also be working in the current version 6.3.0.

**Comment by MrKacafirekCZ** [comment]
Also please try to stay on topic of this specific bug. If you feel like you have found another bug please submit a new issue.

**Comment by Thefatsparrow** [comment]
sorry but thanks!

**Comment by Thefatsparrow** [comment]
one more issue skeletons dont run away from dogs like they do with wild dogs

**Comment by MrKacafirekCZ** [comment]
> one more issue skeletons dont run away from tamed dogs like they do with wild dogs

I don't see how this is related to this issue. As far as I understand this issue is about dog attacking mobs that it shouldn't attack.
